[package]
name = "ferrocene"
version = "0.1.0"
authors = ["G. Queiroz <gabrieljvnq@gmail.com>"]
edition = "2018"
categories = ["authentication", "web-programming"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
tera = "1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"


[dependencies.rocket_contrib]
version = "0.4.6"
default-features = false
features = ["json", "uuid", "serve", "helmet", "tera_templates"]