[package]
name = "ferrocene"
version = "0.1.0"
authors = ["Gabriel Villela Noriega de Queiroz <gabrieljvnq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.11"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
chrono = { version = "0.4", features = ["serde"] }