SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP INDEX IF EXISTS `fk_app_group1` ON `app`;
DROP INDEX IF EXISTS `fk_app_user_scope_scope1_idx` ON `app_user_scope`;
DROP INDEX IF EXISTS `fk_app_user_scope_scope1` ON `app_user_scope`;
DROP INDEX IF EXISTS `fk_app_user_scope_user1_idx` ON `app_user_scope`;
DROP INDEX IF EXISTS `fk_app_user_scope_user1` ON `app_user_scope`;
DROP INDEX IF EXISTS `fk_auto_otp_user1_idx` ON `auto_otp`;
DROP INDEX IF EXISTS `fk_auto_otp_user1` ON `auto_otp`;
DROP INDEX IF EXISTS `fk_group_members_object_type1_idx` ON `group_members`;
DROP INDEX IF EXISTS `fk_kv_object_type1` ON `kv`;
DROP INDEX IF EXISTS `fk_login_handle_user` ON `login_handle`;
DROP INDEX IF EXISTS `fk_recovery_code_user1_idx` ON `basic_otp`;
DROP INDEX IF EXISTS `fk_recovery_code_user1` ON `basic_otp`;
DROP INDEX IF EXISTS `fk_session_real_user_idx` ON `session`;
DROP INDEX IF EXISTS `fk_session_user_idx` ON `session`;
DROP INDEX IF EXISTS `fk_table1_user1_idx` ON `password`;
DROP INDEX IF EXISTS `fk_table1_user1` ON `password`;
DROP INDEX IF EXISTS `fk_webauthn_user1_idx` ON `webauthn`;
DROP INDEX IF EXISTS `fk_webauthn_user1` ON `webauthn`;
DROP INDEX IF EXISTS `from_user_uuid_IDX` ON `policy_delegation`;
DROP INDEX IF EXISTS `ip_addr_peer_IDX` ON `audit`;
DROP INDEX IF EXISTS `ip_addr_real_IDX` ON `audit`;
DROP INDEX IF EXISTS `key_IDX` ON `kv`;
DROP INDEX IF EXISTS `name_UNIQUE` ON `group`;
DROP INDEX IF EXISTS `name_UNIQUE` ON `password`;
DROP INDEX IF EXISTS `name_UNIQUE` ON `scope`;
DROP INDEX IF EXISTS `name_UNIQUE` ON `webauthn`;
DROP INDEX IF EXISTS `subject_uuid_IDX` ON `audit`;
DROP INDEX IF EXISTS `title_UNIQUE` ON `policy_rule`;
DROP INDEX IF EXISTS `to_group_uuid_IDX` ON `policy_delegation`;
DROP INDEX IF EXISTS `to_user_uuid_IDX` ON `policy_delegation`;
DROP INDEX IF EXISTS `user_uuid_IDX` ON `login_handle`;
DROP INDEX IF EXISTS `users_group_UNIQUE` ON `app`;
DROP INDEX IF EXISTS `uuid_IDX` ON `kv`;
DROP INDEX IF EXISTS `valid_until_IDX` ON `policy_delegation`;
DROP INDEX IF EXISTS `when_IDX` ON `audit`;

DROP TABLE IF EXISTS `app`;
DROP TABLE IF EXISTS `login_handle`;
DROP TABLE IF EXISTS `app_user_scope`;
DROP TABLE IF EXISTS `audit`;
DROP TABLE IF EXISTS `auto_otp`;
DROP TABLE IF EXISTS `basic_otp`;
DROP TABLE IF EXISTS `group`;
DROP TABLE IF EXISTS `group_members`;
DROP TABLE IF EXISTS `group_members_view`;
DROP TABLE IF EXISTS `history`;
DROP TABLE IF EXISTS `kv`;
DROP TABLE IF EXISTS `object_type`;
DROP TABLE IF EXISTS `password`;
DROP TABLE IF EXISTS `policy_rule`;
DROP TABLE IF EXISTS `scope`;
DROP TABLE IF EXISTS `session`;
DROP TABLE IF EXISTS `session_view`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `webauthn`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;