SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE `ferrocene`.`user` ;

DROP TABLE `ferrocene`.`sessions` ;

DROP TABLE `ferrocene`.`object_type` ;

DROP TABLE `ferrocene`.`login_handle` ;

DROP TABLE `ferrocene`.`kv` ;

DROP TABLE `ferrocene`.`group_members` ;

DROP TABLE `ferrocene`.`group` ;

DROP TABLE `ferrocene`.`audit` ;

DROP TABLE `ferrocene`.`app` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;