-- MySQL Script generated by MySQL Workbench
-- dom 17 jan 2021 17:21:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ferrocene
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `app`
-- -----------------------------------------------------
CREATE TABLE `app` (
  `uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(1024) NOT NULL,
  `key` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `audit`
-- -----------------------------------------------------
CREATE TABLE `audit` (
  `audit_id` INT(11) NOT NULL,
  `ip_addr` VARBINARY(16) NULL DEFAULT NULL COMMENT 'Use INET6_ATON and INET6_ATON',
  `when` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `subject_uuid` CHAR(36) CHARACTER SET 'ascii' NULL DEFAULT NULL,
  `level` CHAR(1) NOT NULL,
  `msg_code` VARCHAR(190) NOT NULL,
  `msg_fmt` MEDIUMTEXT NOT NULL,
  `kv` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`audit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `subject_uuid_IDX` ON `audit` (`subject_uuid` ASC);

CREATE INDEX `ip_addr_IDX` ON `audit` (`ip_addr` ASC);

CREATE INDEX `when_IDX` ON `audit` (`when` ASC);


-- -----------------------------------------------------
-- Table `group`
-- -----------------------------------------------------
CREATE TABLE `group` (
  `uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `name` VARCHAR(190) NOT NULL,
  `comments` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `name_UNIQUE` ON `group` (`name` ASC);


-- -----------------------------------------------------
-- Table `group_members`
-- -----------------------------------------------------
CREATE TABLE `group_members` (
  `group_uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `member_uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`group_uuid`, `member_uuid`),
  CONSTRAINT `fk_group_members_group`
    FOREIGN KEY (`group_uuid`)
    REFERENCES `group` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kv`
-- -----------------------------------------------------
CREATE TABLE `kv` (
  `row_id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `key` VARCHAR(190) NOT NULL,
  `value` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`row_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `uuid_IDX` ON `kv` (`uuid` ASC);

CREATE INDEX `key_IDX` ON `kv` (`key` ASC);


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE `user` (
  `uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `display_name` VARCHAR(190) NOT NULL,
  `auth_info` MEDIUMTEXT NOT NULL DEFAULT '{}',
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `login_handle`
-- -----------------------------------------------------
CREATE TABLE `login_handle` (
  `handle` VARCHAR(190) NOT NULL,
  `user_uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `kind` VARCHAR(50) NOT NULL DEFAULT 'username',
  PRIMARY KEY (`handle`),
  CONSTRAINT `fk_handle_user`
    FOREIGN KEY (`user_uuid`)
    REFERENCES `user` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `user_uuid_IDX` ON `login_handle` (`user_uuid` ASC);


-- -----------------------------------------------------
-- Table `object_type`
-- -----------------------------------------------------
CREATE TABLE `object_type` (
  `uuid` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `type` CHAR(5) NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sessions`
-- -----------------------------------------------------
CREATE TABLE `sessions` (
  `session_uuid` CHAR(36) CHARACTER SET 'ascii' COLLATE 'ascii_general_ci' NOT NULL,
  `user_uuid` CHAR(36) CHARACTER SET 'ascii' COLLATE 'ascii_general_ci' NOT NULL,
  `login_on` DATETIME NOT NULL,
  `valid_until` DATETIME NOT NULL,
  `info` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NOT NULL DEFAULT '{}',
  PRIMARY KEY (`session_uuid`),
  CONSTRAINT `fk_sessions_user1`
    FOREIGN KEY (`user_uuid`)
    REFERENCES `user` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `fk_sessions_user1_idx` ON `sessions` (`user_uuid` ASC);


CREATE TRIGGER `group_AFTER_INSERT`
AFTER INSERT ON `group`
FOR EACH ROW
BEGIN
	INSERT INTO `object_type` (`uuid`, `type`) VALUES (NEW.`uuid`, 'G');
END;

CREATE TRIGGER `group_AFTER_DELETE`
AFTER DELETE ON `group`
FOR EACH ROW
BEGIN
	DELETE FROM `object_type` WHERE `uuid` = OLD.`uuid`;
	DELETE FROM `kv` WHERE `uuid` = OLD.`uuid`;
END;

CREATE TRIGGER `user_AFTER_DELETE`
AFTER DELETE ON `user`
FOR EACH ROW
BEGIN
	DELETE FROM `object_type` WHERE `uuid` = OLD.`uuid`;
    DELETE FROM `login_handle` WHERE `login_uuid` = OLD.`uuid`;
    DELETE FROM `kv` WHERE `uuid` = OLD.`uuid`;
END;

CREATE TRIGGER `user_AFTER_INSERT`
AFTER INSERT ON `user`
FOR EACH ROW
BEGIN
    INSERT INTO `object_type` (`uuid`, `type`) VALUES (NEW.`uuid`, 'U');
END;

CREATE TRIGGER `app_AFTER_DELETE`
AFTER DELETE ON `app`
FOR EACH ROW
BEGIN
	DELETE FROM `object_type` WHERE `uuid` = OLD.`uuid`;
    DELETE FROM `kv` WHERE `uuid` = OLD.`uuid`;
END;

CREATE TRIGGER `app_AFTER_INSERT`
AFTER INSERT ON `app`
FOR EACH ROW
BEGIN
    INSERT INTO `object_type` (`uuid`, `type`) VALUES (NEW.`uuid`, 'A');
END;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;